In [13]:
import os
import sys
import numpy as np
import matplotlib.pyplot as plt
import torch

from system_config import *
from utility import get_data_tensor, safe_legend
from joint_upganet import JointUPGANet, get_joint_loss, initialize_joint, project_to_simplex_rows


In [3]:
H_train, _ = get_data_tensor(data_source)
print("H_train shape:", H_train.shape)

M_matrix = (A_dot.conj().T @ R_N_inv @ A_dot).to(H_train.device)
print("M_matrix shape:", M_matrix.shape)

H_train shape: torch.Size([1, 4480, 4, 64])
M_matrix shape: torch.Size([64, 64])


In [4]:
def to_joint_channel(H_kb: torch.Tensor) -> torch.Tensor:
    """(K, B, M, Nt) -> (B, Nt, M) using the single frequency band."""
    return H_kb[0].transpose(1, 2)   # strip K, swap users<->antennas

In [7]:
i_batch = 1
H_shuffled = torch.transpose(H_train, 0, 1)[np.random.permutation(len(H_train[0]))]
H_batch = torch.transpose(H_shuffled[i_batch:i_batch + batch_size], 0, 1)
cur_bs = H_batch.shape[1]
snr_dB_train = np.random.permutation(np.tile(snr_dB_list, batch_size // len(snr_dB_list)))[:cur_bs]
snr_train = torch.tensor(10 ** (snr_dB_train / 10), dtype=torch.float32, device=device)

H_joint = to_joint_channel(H_batch).to(device) 
F0, W0 = initialize_joint(H_joint, snr_train, Nrf)
print(F0.shape, W0.shape)

torch.Size([1120, 64, 4]) torch.Size([1120, 4, 4])


In [8]:
from joint_upganet import build_fixed_subconnected_mask

S = build_fixed_subconnected_mask(Nt, Nrf)
print(S)

tensor([[1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0.,

In [17]:
S = torch.tensor([
    [0.5, 0.7],
    [0.2, 0.2],
    [0.9, 0.1]
])

print(S)

S_hat = project_to_simplex_rows(S)
print(S_hat)

tensor([[0.5000, 0.7000],
        [0.2000, 0.2000],
        [0.9000, 0.1000]])
tensor([[0.4000, 0.6000],
        [0.5000, 0.5000],
        [0.9000, 0.1000]])


In [20]:
_, H_test0 = get_data_tensor(data_source)
print(f'Size of the test set', H_test0.shape)

H_test = H_test0[:, :test_size, :, :]
print(f'Size of the test set', H_test.shape)

Size of the test set torch.Size([1, 30, 4, 64])
Size of the test set torch.Size([1, 30, 4, 64])


In [7]:
from utility import load_data_matlab, get_data_tensor
from system_config import data_source, data_path_train, data_path_test

H_train, _ = get_data_tensor(data_source)
print(H_train[0].shape)



torch.Size([500, 4, 64])
