In [4]:
import torch
from system_config import Nt, delta, desired_angle_rad
n_indices = torch.arange(Nt, dtype=torch.float32)
desired_angle_rad_torch = torch.tensor(desired_angle_rad, dtype=torch.float32)
phase = 1j* 2 * torch.pi * delta * torch.sin(desired_angle_rad_torch) * n_indices
a_phi_0 = torch.exp(phase)  # shape: (Nt, 1)
a_dot_phi_0 = ((1j * 2 * torch.pi * delta * torch.cos(desired_angle_rad_torch) * n_indices) * a_phi_0)

a_phi_0 = a_phi_0.unsqueeze(1)  # shape: (Nt, 1)
a_dot_phi_0 = a_dot_phi_0.unsqueeze(1)  # shape: (Nt, 1)

64 Tx antennas, 4 users, 4 RF chains, 1 frequency, 0 LoS users, 0 normalize tau


In [5]:
A_dot = a_dot_phi_0 @ a_phi_0.transpose(0, 1) + a_phi_0 @ a_dot_phi_0.transpose(0, 1)
print(A_dot.shape)

torch.Size([64, 64])


In [6]:
R_N = torch.eye(Nt)  # noise covariance matrix
R_N_inv = torch.linalg.inv(R_N)  # inverse of noise covariance matrix
print(R_N_inv.shape)

torch.Size([64, 64])


In [7]:

from utility import initialize, get_data_tensor
from system_config import initial_normalization, data_source, snr_dB_list

import numpy as np

H_train, H_test0 = get_data_tensor(data_source)
H_shuffeld = torch.transpose(H_train, 0, 1)[np.random.permutation(len(H_train[0]))]
H = torch.transpose(H_shuffeld[0:4], 0, 1)
snr_dB_train = np.random.choice(snr_dB_list)
snr_train = 10 ** (snr_dB_train / 10)
rate_init, F, W = initialize(H, snr_train, initial_normalization)

In [8]:
print(f'Shape of the metrixes: F.shape = {F.shape}, W.shape = {W.shape} and H.shape = {H.shape}' )

Shape of the metrixes: F.shape = torch.Size([1, 4, 64, 4]), W.shape = torch.Size([1, 4, 4, 4]) and H.shape = torch.Size([1, 4, 4, 64])


In [9]:
def get_grad_F_CRB(F, W, xi_0, A_dot, R_N_inv):

    # match the data type of A_dot and R_N_inv with F
    A_dot = A_dot.to(F.dtype)
    R_N_inv = R_N_inv.to(F.dtype)

    # reshape A_dot and R_N_inv for batch processing
    A_dot = A_dot.unsqueeze(0).unsqueeze(0) # [1, 1, Nt, Nt]
    R_N_inv = R_N_inv.unsqueeze(0).unsqueeze(0) # [1, 1, Nr, Nr]

    A_dot_H = A_dot.conj().transpose(-2, -1)
    W_H = W.conj().transpose(-2, -1)
    F_H = F.conj().transpose(-2, -1)
    
    M = A_dot_H @ R_N_inv @ A_dot

    inner_mat = W_H @ F_H @ M @ F @ W
    batch_trace = (torch.diagonal(inner_mat, dim1=-2, dim2=-1).sum(-1))
    
    numerator = M @ F @ W @ W_H
    denominator = batch_trace.view(1, -1, 1, 1)
    
    grad_F_CRB = numerator / denominator
    
    return grad_F_CRB

In [10]:
from system_config import xi_0
grad_F_CRB = get_grad_F_CRB(F, W, xi_0, A_dot, R_N_inv)

In [12]:
print(grad_F_CRB.shape)

torch.Size([1, 4, 64, 4])


In [13]:
def get_grad_W_CRB(F, W, xi_0, A_dot, R_N_inv):

    A_dot = A_dot.to(F.dtype)
    R_N_inv = R_N_inv.to(F.dtype)

    A_dot = A_dot.unsqueeze(0).unsqueeze(0) # [1, 1, Nt, Nt]
    R_N_inv = R_N_inv.unsqueeze(0).unsqueeze(0) # [1, 1, Nr, Nr]

    A_dot_H = A_dot.conj().transpose(-2, -1)
    W_H = W.conj().transpose(-2, -1)
    F_H = F.conj().transpose(-2, -1)


    M = A_dot_H @ R_N_inv @ A_dot
    inner_mat = W_H @ F_H @ M @ F @ W
    batch_trace = (torch.diagonal(inner_mat, dim1=-2, dim2=-1).sum(-1))
    
    numerator = F_H @ M @ F @ W
    denominator = batch_trace.view(1, -1, 1, 1)
    grad_W_CRB = numerator / denominator
    return grad_W_CRB

In [14]:
from system_config import xi_0
get_grad_W_CRB = get_grad_W_CRB(F, W, xi_0, A_dot, R_N_inv)

In [15]:
print(get_grad_W_CRB)

tensor([[[[ 1.8862-1.3193e-01j,  1.5694-4.4937e-01j,  0.4553+1.1436e+00j,
            2.1151+2.8313e+00j],
          [ 1.2477+1.8694e-01j,  1.1253-6.3038e-02j,  0.1153+8.2943e-01j,
            0.9700+2.1958e+00j],
          [ 0.0829-8.0760e-01j, -0.0903-7.1173e-01j,  0.5308-1.1093e-01j,
            1.3688-7.0708e-01j],
          [ 0.8808-1.3590e+00j,  0.5048-1.3332e+00j,  1.0298+2.8996e-01j,
            3.0603+1.1543e-02j]],

         [[ 0.2482-1.0322e-01j, -0.2024-2.8528e-02j,  0.7246-2.4925e-01j,
            0.6135-5.8694e-01j],
          [-0.1926+1.1421e-01j,  0.1800+2.0323e-03j, -0.5724+2.8952e-01j,
           -0.4406+5.7631e-01j],
          [ 0.7030-1.4182e-02j, -0.4681-2.6924e-01j,  2.0037+8.8178e-02j,
            2.0676-8.4886e-01j],
          [ 1.0396+2.8448e-01j, -0.5653-6.1746e-01j,  2.9048+1.0076e+00j,
            3.4471-3.3953e-01j]],

         [[ 0.6630+9.1835e-02j,  0.1800-5.8550e-01j, -0.0845-4.0095e-02j,
           -0.8283-1.4505e+00j],
          [-0.0111+5.7789e-01j,  

In [16]:
from utility import normalize
def get_crb(H, F, W, xi_0, A_dot, R_N_inv, Pt):
    F, W = normalize(F, W, H, Pt)
    
    A_dot = A_dot.to(F.dtype)
    R_N_inv = R_N_inv.to(F.dtype)

    A_dot = A_dot.unsqueeze(0).unsqueeze(0) # [1, 1, Nt, Nt]
    R_N_inv = R_N_inv.unsqueeze(0).unsqueeze(0) # [1, 1, Nr, Nr]

    A_dot_H = A_dot.conj().transpose(-2, -1)
    W_H = W.conj().transpose(-2, -1)
    F_H = F.conj().transpose(-2, -1)
    
    M = A_dot_H @ R_N_inv @ A_dot
    inner_mat = W_H @ F_H @ M @ F @ W
    batch_trace = (torch.diagonal(inner_mat, dim1=-2, dim2=-1).sum(-1))

    denominator = 2 * (torch.abs(torch.tensor(xi_0))**2) * batch_trace.view(1, -1, 1, 1)

    crb = torch.log(1 / denominator)
    
    return crb
    

In [17]:
crb = get_crb(H, F, W, xi_0, A_dot, R_N_inv, snr_train)
print(crb)

tensor([[[[-15.4586+4.3434e-08j]],

         [[-16.2217+2.3323e-07j]],

         [[-16.8594+9.4928e-09j]],

         [[-15.7290+2.1903e-08j]]]])


In [19]:

from utility import get_sum_rate, get_crb_fe
from system_config import OMEGA, normalize_tau

def get_sum_loss(F, W, H, xi_0, A_dot, R_N_inv, Pt):
    sum_rate = get_sum_rate(H, F, W, Pt)
    # loss = -(sum_rate - OMEGA * sum_error)# / (K * batch_size)

    # For CRB-based loss, we can directly use the CRB value as the loss, since we want to minimize it.
    crb = get_crb_fe(H, F, W, xi_0, A_dot, R_N_inv, Pt)
    mean_crb = torch.mean(crb)
    loss = -(sum_rate - OMEGA * mean_crb)
    return loss

In [24]:
from PGA_models import get_grad_F_com
grad_F_com = get_grad_F_com(H, F, W)
grad_vec_com = grad_F_com.reshape(64, -1)
print(f'Shape of grad_vec_com: {grad_vec_com.shape}')
print(f'Shape of grad_F_com: {grad_F_com.shape}')

Shape of grad_vec_com: torch.Size([64, 16])
Shape of grad_F_com: torch.Size([1, 4, 64, 4])


In [30]:
x = torch.tensor([1, 2, 3, 4])
x = x.unsqueeze(1)
print(f'Shape of x: {x.shape}')

Shape of x: torch.Size([4, 1])


In [ ]:
loss = get_sum_loss(F, W, H, xi_0, A_dot, R_N_inv, snr_train)
print(loss)

tensor(-9.5626-4.3035e-08j)


In [ ]:
from system_config import step_size_UPGA_J20
print(step_size_UPGA_J20[2][3][0])

tensor(0.0100, grad_fn=<SelectBackward0>)


In [ ]:
import torch
from system_config import step_size_fixed, Nt, M, Nrf
# M, Nrf, Nt = torch.tensor(M), torch.tensor(Nrf), torch.tensor(Nt)
step_size_lambda = torch.eye(Nt, Nt) * step_size_fixed
step_size_lambda.requires_grad_()

step_size_mu = torch.eye(M, M) * step_size_fixed
step_size_mu.requires_grad_()

tensor([[0.0100, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0100, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0100, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0100]], requires_grad=True)

In [ ]:
print(step_size_lambda.shape)

torch.Size([64, 64])


In [5]:
from system_config import batch_size, snr_dB_list
import numpy as np
cur_bs = batch_size
snr_dB_train = np.random.permutation(np.tile(snr_dB_list, batch_size // len(snr_dB_list)))[:cur_bs]
snr_dB_train 

array([10., 12., 12.,  8.,  4.,  6.,  0., 10.,  8.,  2.,  2.,  4.,  8.,
       10.,  2.,  8.,  2.,  4.,  0.,  6.,  0.,  6.,  0., 12.,  4.,  6.,
       12., 10.])